// Code generated by goctl. DO NOT EDIT!

package sysadmin

import (
	"time"
)

type SysPermMenu struct {
	Id           int64     `json:"id" gorm:"column:id" column:"id"`                                  // 编号
	ParentId     int64     `json:"parent_id" gorm:"column:parent_id" column:"parent_id"`             // 父级id
	Name         string    `json:"name" gorm:"column:name" column:"name"`                            // 名称
	Router       string    `json:"router" gorm:"column:router" column:"router"`                      // 路由
	Perms        string    `json:"perms" gorm:"column:perms" column:"perms"`                         // 权限
	Type         int64     `json:"type" gorm:"column:type" column:"type"`                            // 0=目录 1=菜单 2=权限
	Icon         string    `json:"icon" gorm:"column:icon" column:"icon"`                            // 图标
	OrderNum     int64     `json:"order_num" gorm:"column:order_num" column:"order_num"`             // 排序值
	ViewPath     string    `json:"view_path" gorm:"column:view_path" column:"view_path"`             // 页面路径
	IsShow       int64     `json:"is_show" gorm:"column:is_show" column:"is_show"`                   // 0=隐藏 1=显示
	ActiveRouter string    `json:"active_router" gorm:"column:active_router" column:"active_router"` // 当前激活的菜单
	Created      time.Time `json:"created" gorm:"column:created" column:"created"`                   // 创建时间
	Updated      time.Time `json:"updated" gorm:"column:updated" column:"updated"`                   // 更新时间
}

func (ins *SysPermMenu) TableName() string {
	return "`sys_perm_menu`"
}

func (ins *SysPermMenu) GetPKColumnName() string {
	return "id"
}

func (ins *SysPermMenu) GetPkValue() interface{} {
	return ins.Id
}

func (ins *SysPermMenu) SetTime() {
	hasPkValue := false
	val := ins.GetPkValue()
	switch val.(type) {
	case int:
		hasPkValue = val.(int) > 0
	case int64:
		hasPkValue = val.(int64) > 0
	case uint8:
		hasPkValue = val.(uint8) > 0
	case int32:
		hasPkValue = val.(int32) > 0
	case string:
		hasPkValue = val.(string) != ""
	}
	if !hasPkValue {
		ins.Created = time.Now()
	}
	ins.Updated = time.Now()

	return
}
