// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"gozore-mall/app/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {

}
